//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulgarianDayOfWeek.Client.BulgarianDayOfWeekService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BulgarianDayOfWeekService.IBulgarianDayOfWeekCalculator")]
    public interface IBulgarianDayOfWeekCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBulgarianDayOfWeekCalculator/GetDayOfWeek", ReplyAction="http://tempuri.org/IBulgarianDayOfWeekCalculator/GetDayOfWeekResponse")]
        string GetDayOfWeek(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBulgarianDayOfWeekCalculator/GetDayOfWeek", ReplyAction="http://tempuri.org/IBulgarianDayOfWeekCalculator/GetDayOfWeekResponse")]
        System.Threading.Tasks.Task<string> GetDayOfWeekAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBulgarianDayOfWeekCalculatorChannel : BulgarianDayOfWeek.Client.BulgarianDayOfWeekService.IBulgarianDayOfWeekCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BulgarianDayOfWeekCalculatorClient : System.ServiceModel.ClientBase<BulgarianDayOfWeek.Client.BulgarianDayOfWeekService.IBulgarianDayOfWeekCalculator>, BulgarianDayOfWeek.Client.BulgarianDayOfWeekService.IBulgarianDayOfWeekCalculator {
        
        public BulgarianDayOfWeekCalculatorClient() {
        }
        
        public BulgarianDayOfWeekCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BulgarianDayOfWeekCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BulgarianDayOfWeekCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BulgarianDayOfWeekCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayOfWeek(System.DateTime date) {
            return base.Channel.GetDayOfWeek(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayOfWeekAsync(System.DateTime date) {
            return base.Channel.GetDayOfWeekAsync(date);
        }
    }
}
