//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStringCounterInText")]
public interface IStringCounterInText
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCounterInText/CountOccurrance", ReplyAction="http://tempuri.org/IStringCounterInText/CountOccurranceResponse")]
    int CountOccurrance(string text, string str);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCounterInText/CountOccurrance", ReplyAction="http://tempuri.org/IStringCounterInText/CountOccurranceResponse")]
    System.Threading.Tasks.Task<int> CountOccurranceAsync(string text, string str);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStringCounterInTextChannel : IStringCounterInText, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StringCounterInTextClient : System.ServiceModel.ClientBase<IStringCounterInText>, IStringCounterInText
{
    
    public StringCounterInTextClient()
    {
    }
    
    public StringCounterInTextClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StringCounterInTextClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringCounterInTextClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringCounterInTextClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int CountOccurrance(string text, string str)
    {
        return base.Channel.CountOccurrance(text, str);
    }
    
    public System.Threading.Tasks.Task<int> CountOccurranceAsync(string text, string str)
    {
        return base.Channel.CountOccurranceAsync(text, str);
    }
}
